language: java
jdk: oraclejdk11

script: mvn clean verify

services:
  - postgresql

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - sparrowgv@mail.ru
    on_success: never
    on_failure: always