server:
  port: 8090
  servlet:
    context-path: /backend

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog-master.xml